server:
  port: 8080
  servlet:
    context-path: /
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5level) --- [%-15thread] %cyan(%-50logger{50}):%msg%n'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moma?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Lith19890118
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    connect-timeout: 10s
    lettuce:
      pool:
        max-active: 8
        max-wait: 200s
        max-idle: 8
        min-idle: 0
  mail:
    username: 1182862810@qq.com
    password: pieoahcwrzeabahb
    host: smtp.qq.com
    default-encoding: UTF-8
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    check-template-location: true
    template-loader-path: classpath:/templates/
    suffix: .ftl


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml